name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update Backend and Restart
        run: |
          cd /home/miha/srv/netcourse-backend

          git pull origin main

          cd /home/miha/srv
          docker compose up -d --build netcourse-backend

          docker system prune -f
