name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Backend and Restart
        run: |
          docker compose -f /home/miha/srv/docker-compose.yml -p srv up -d --build netcourse-backend
          
          docker system prune -f

