name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Backend and Restart
        env:
          DOCKER_HOST: unix:///var/run/docker.sock
        run: |
          docker build -t netcourse-backend:latest .
          
          docker stop netcourse-backend || true
          docker rm netcourse-backend || true

          docker run -d --name netcourse-backend --volumes-from netcourse-backend netcourse-backend:latest || \
 
          docker system prune -f


